[tool.poetry]
name = "lol-audio-unpack"
version = "0.1.0"
description = "英雄联盟游戏音频文件解包工具"
authors = ["Virace <Virace@aliyun.com>"]
readme = "README.md"
packages = [{include = "lol_audio_unpack"}]

[tool.poetry.dependencies]
python = "^3.10"
lol-voice = "^1.0.0a9"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
